services:
  backend:
    build:
      context: ./MAA-Meditation-App/MAA-Project/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  admin:
    build:
      context: ./MAA-Meditation-App/MAA-Project/admin
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: always
